name: Release CI
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[no-ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Build TypeScript
        run: yarn build
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: "GameAction Bot"
          GIT_AUTHOR_EMAIL: "me@remy.ovh"
          GIT_COMMITTER_NAME: "GameAction Bot"
          GIT_COMMITTER_EMAIL: "me@remy.ovh"
